// ─── Head Waste Statement ────────────────────────────────────────────────────
// Head/shell waste generated by the two processing stages, per location.
//
// Waste is charged against what goes INTO each stage, not what comes out:
//   HON → HL : heads removed  = 32% of HON processed
//              (matches YIELD_CHART, whose HON→HL yields run 64–71%)
//   HL  → VA : shell/vein loss = 18% of HL consumed
//              (matches HLVA_YIELD_CHART, whose PD yields run 79–83%)
//
// EZPL is easy-peel — the shell is scored, not removed — so it carries
// effectively no weight loss (99–99.5% yield in the chart). HL consumed by EZPL
// batches is therefore excluded from the VA waste base, though its VA output
// still counts toward the location's produced quantity.

import type { YieldEntry, HlVaEntry } from '@/types';

export const HEAD_WASTE_RATE = 0.32; // of HON processed
export const VA_WASTE_RATE = 0.18;   // of HL consumed

/**
 * Each waste figure is also carried at a multiple of the raw quantity. The
 * factor is set by the user on the report and remembered in localStorage under
 * WASTE_MULTIPLIER_KEY; this is only the starting value.
 */
export const DEFAULT_WASTE_MULTIPLIER = 2.5;
export const WASTE_MULTIPLIER_KEY = 'headWasteMultiplier';

/** Varieties that generate no meaningful waste at the HL → VA stage. */
export const NO_WASTE_VARIETIES = ['EZPL'];

/** The plant's own locations, in report order. Everything else is hired outside capacity. */
export const IN_HOUSE_LOCATIONS: { key: string; label: string }[] = [
  { key: 'ppc1', label: 'PPC 1' },
  { key: 'ppc2', label: 'PPC 2' },
  { key: 'plant', label: 'Plant' },
];

/**
 * Normalise a location name for comparison — names are user-entered and carry
 * spaces inconsistently ('PPC 1' vs 'PPC1' vs 'ppc-1').
 */
export function locationKey(name: string | null | undefined): string {
  return (name || '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function isInHouseLocation(name: string | null | undefined): boolean {
  const key = locationKey(name);
  return IN_HOUSE_LOCATIONS.some((l) => l.key === key);
}

function isNoWasteVariety(variety: string | null | undefined): boolean {
  return NO_WASTE_VARIETIES.includes((variety || '').trim().toUpperCase());
}

export interface HeadWasteRow {
  key: string;
  label: string;
  hon: number;       // HON processed (HON → HL input)
  hl: number;        // HL produced (HON → HL output)
  headWaste: number; // hon × 32%
  headWasteX: number; // headWaste × multiplier
  hlUsed: number;    // HL consumed by HL → VA, excluding no-waste varieties
  hlEzpl: number;    // HL consumed by EZPL batches — excluded from the waste base
  va: number;        // VA produced, all varieties
  vaWaste: number;   // hlUsed × 18%
  vaWasteX: number;  // vaWaste × multiplier
  totalWaste: number;
  totalWasteX: number; // totalWaste × multiplier
}

const emptyRow = (key: string, label: string): HeadWasteRow => ({
  key, label, hon: 0, hl: 0, headWaste: 0, headWasteX: 0, hlUsed: 0, hlEzpl: 0, va: 0,
  vaWaste: 0, vaWasteX: 0, totalWaste: 0, totalWasteX: 0,
});

/** Fill in the derived waste figures once the raw quantities are summed. */
function withWaste(row: HeadWasteRow, multiplier: number): HeadWasteRow {
  row.headWaste = row.hon * HEAD_WASTE_RATE;
  row.vaWaste = row.hlUsed * VA_WASTE_RATE;
  row.totalWaste = row.headWaste + row.vaWaste;
  row.headWasteX = row.headWaste * multiplier;
  row.vaWasteX = row.vaWaste * multiplier;
  row.totalWasteX = row.totalWaste * multiplier;
  return row;
}

function accumulate(target: HeadWasteRow, source: HeadWasteRow): void {
  target.hon += source.hon;
  target.hl += source.hl;
  target.hlUsed += source.hlUsed;
  target.hlEzpl += source.hlEzpl;
  target.va += source.va;
}

export interface HeadWasteStatement {
  inHouseRows: HeadWasteRow[];  // always all three, zero-filled when idle
  inHouseTotal: HeadWasteRow;
}

export function buildHeadWasteStatement(
  yieldEntries: YieldEntry[],
  hlVaEntries: HlVaEntry[],
  multiplier: number = DEFAULT_WASTE_MULTIPLIER
): HeadWasteStatement {
  const inHouse = new Map<string, HeadWasteRow>(
    IN_HOUSE_LOCATIONS.map((l) => [l.key, emptyRow(l.key, l.label)])
  );

  // Hired outside capacity isn't our waste to account for — those entries are skipped
  const bucket = (name: string | null | undefined): HeadWasteRow | undefined =>
    inHouse.get(locationKey(name));

  yieldEntries.forEach((e) => {
    const row = bucket(e.location?.name);
    if (!row) return;
    row.hon += Number(e.hon_kgs) || 0;
    row.hl += Number(e.hl_kgs) || 0;
  });

  hlVaEntries.forEach((e) => {
    const row = bucket(e.location?.name);
    if (!row) return;
    const hl = Number(e.hl_kgs) || 0;
    row.va += Number(e.va_kgs) || 0;
    if (isNoWasteVariety(e.variety)) {
      row.hlEzpl += hl;
    } else {
      row.hlUsed += hl;
    }
  });

  const inHouseRows = IN_HOUSE_LOCATIONS.map((l) => withWaste(inHouse.get(l.key)!, multiplier));

  const inHouseTotal = emptyRow('inhouse-total', 'Total (In-house)');
  inHouseRows.forEach((r) => accumulate(inHouseTotal, r));
  withWaste(inHouseTotal, multiplier);

  return { inHouseRows, inHouseTotal };
}
